# --- ETAPA 1: CONSTRUCCIÓN ---
FROM node:20-alpine AS builder

WORKDIR /app
ENV NX_DAEMON=false

COPY package.json package-lock.json ./
# Instalamos TODO (incluyendo devDependencies como prisma CLI)
RUN npm install --legacy-peer-deps

COPY nx.json tsconfig.base.json ./
COPY apps ./apps
COPY prisma ./prisma

# Generamos el cliente con la versión correcta (6.19.1)
RUN npx prisma generate

ARG SERVICE_NAME
RUN npx nx build ${SERVICE_NAME} --prod --skip-nx-cache

# --- ETAPA 2: EJECUCIÓN (PRODUCCIÓN) ---
FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./

# 1. Instalamos dependencias de producción
RUN npm install --only=production --legacy-peer-deps

# 2. 🚩 FIX CRÍTICO: Instalamos el CLI de Prisma MANUALMENTE en la versión exacta
# Esto evita que 'npx' descargue la versión 7.3.0 al arrancar
RUN npm install prisma@6.19.1 --save-dev

# 3. Copiamos archivos necesarios
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/prisma ./prisma

ARG SERVICE_NAME
COPY --from=builder /app/apps/backend/${SERVICE_NAME}/dist ./dist


ENV PORT=3000
EXPOSE 3000

# 🚩 CAMBIO FINAL: Usamos 'db push' en lugar de 'migrate deploy'
# Esto crea las tablas SÍ O SÍ, sin importar si tienes historial de migraciones o no.
CMD npx prisma db push --schema=/app/prisma/schema.prisma && node dist/main.js