server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # --- RUTAS A MICROSERVICIOS ---

    # Data Ingestion (3000)
    location /api/ingestion/ {
        proxy_pass http://data-ingestion-service:3000/api/ingestion/;
        proxy_set_header Host $host;
    }

    # Structure (3001) - ¡AHORA SÍ AL SERVICIO REAL!
    location /api/structure/ {
        proxy_pass http://academic-structure-service:3001/api/structure/;
        proxy_set_header Host $host;
    }

    # Auth (3002)
    location /api/auth/ {
        proxy_pass http://auth-service:3002/api/auth/;
        proxy_set_header Host $host;
    }

    # Audit (3003)
    location /api/audit/ {
        proxy_pass http://audit-service:3003/api/audit/;
        proxy_set_header Host $host;
    }

    # Calculation - GO (3004)
    location /api/calculation/ {
        proxy_pass http://capacity-calculation-service:3004/api/calculation/;
        proxy_set_header Host $host;
    }

    # Rules (3005)
    location /api/rules/ {
        proxy_pass http://rules-configuration-service:3005/api/rules/;
        proxy_set_header Host $host;
    }

    # Analytics (3006)
    location /api/analytics/ {
        proxy_pass http://analytics-service:3006/api/analytics/;
        proxy_set_header Host $host;
    }

    # Notifications (3007)
    location /api/notifications/ {
        proxy_pass http://notification-service:3007/api/notifications/;
        proxy_set_header Host $host;
    }

    # Requests (3008)
    location /api/requests/ {
        proxy_pass http://request-service:3008/api/requests/;
        proxy_set_header Host $host;
    }

    # Management (3009)
    location /api/management/ {
        proxy_pass http://capacity-management-service:3009/api/management/;
        proxy_set_header Host $host;
    }
}