server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # --- RUTAS ---
    
    # 1. Ingesta
    location /api/ingestion/ {
        proxy_pass http://data-ingestion-service:3000/api/ingestion/;
        proxy_set_header Host $host;
    }

    # 2. Estructura (VITAL PARA EL DROPDOWN)
    location /api/structure/ {
        proxy_pass http://academic-structure-service:3001/api/structure/;
        proxy_set_header Host $host;
    }

    # 3. Auth
    location /api/auth/ {
        proxy_pass http://auth-service:3002/api/auth/;
        proxy_set_header Host $host;
    }

    # 4. Audit
    location /api/audit/ {
        proxy_pass http://audit-service:3003/api/audit/;
        proxy_set_header Host $host;
    }

    # 5. Calculation (Go)
    location /api/calculation/ {
        proxy_pass http://capacity-calculation-service:3004/;
    }

    # 6. Rules
    location /api/rules/ {
        proxy_pass http://rules-configuration-service:3005/api/rules/;
        proxy_set_header Host $host;
    }

    # 7. Analytics
    location /api/analytics/ {
        proxy_pass http://analytics-service:3006/api/analytics/;
        proxy_set_header Host $host;
    }

    # 8. Notifications
    location /api/notifications/ {
        proxy_pass http://notification-service:3007/api/notifications/;
        proxy_set_header Host $host;
    }

    # 9. Requests
    location /api/requests/ {
        proxy_pass http://request-service:3008/api/requests/;
        proxy_set_header Host $host;
    }

    # 10. Management
    location /api/management/ {
        proxy_pass http://capacity-management-service:3009/api/management/;
        proxy_set_header Host $host;
    }
}