validate-apps:
    name: Build Microservices (Nx)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # --- NUEVO: Configuración de Go ---
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Ajusta a la versión que uses
          cache: true

      - name: Install Node Dependencies
        run: npm install

      # Opcional: Si tienes un go.mod en la raíz, descarga las dependencias
      - name: Install Go Dependencies
        run: go mod download
      # ---------------------------------

      - name: Build Affected
        run: npx nx affected -t build --base=origin/develop --no-cloud